import { ProjectsSectionType } from '@/lib/types/sections'
import { getId } from '@/lib/utils/helper';


export const projectsSection: ProjectsSectionType = {
    title: 'my projects',
    projects: [
    {
        id: getId(),
        name: 'Job Portal',
        url: 'https://job-portal.42web.io/',
        repo: 'https://github.com/KhushiramMeena/Job-Portal/',
        img: '/project-img/p1-job-portal.png',
        year: 2023,
        tags: ['PHP', 'MySQL'],
    },
    {
        id: getId(),
        name: 'Question Paper Generator',
        url: 'https://question-paper-generator.vercel.app/',
        repo: 'https://github.com/KhushiramMeena/Question-Paper',
        img: '/project-img/p2-question-paper.png',
        year: 2023,
        tags: ['HTML', 'CSS', 'Bootstrap','JavaScript'],
    },
    {
        id: getId(),
        name: 'Crypto Tax Calculator',
        url: 'https://cryptotaxcalculator.vercel.app/',
        repo: 'https://github.com/KhushiramMeena/Aus_Tax_Cal',
        img: '/project-img/p3-crypto-tax.png',
        year: 2023,
        tags: ['React','Next.Js','Tailwind-CSS'],
    },
    {
        id: getId(),
        name: 'Invoice Generator',
        url: 'https://invc-system.vercel.app/',
        repo: 'https://github.com/KhushiramMeena/Invoice-System',
        img: '/project-img/p4-invoice-sys.png',
        year: 2022,
        tags: ['React','Redux'],
    },
    {
        id: getId(),
        name: 'Animated UI',
        url: 'https://density-frontend-nine.vercel.app/',
        repo: 'https://github.com/KhushiramMeena/density-frontend',
        img: '/project-img/p5-animation.png',
        year: 2022,
        tags: ['React','Next.Js', 'TypeScript'],
    },
    {
        id: getId(),
        name: 'Weather Application',
        url: 'https://weather-wb-app.netlify.app/',
        repo: 'https://github.com/KhushiramMeena/weather-application',
        img: '/project-img/p6-weather.png',
        year: 2022,
        tags: ['React', 'CSS'],
    },
    {
        id: getId(),
        name: 'Money Tracker',
        url: 'https://todo-kv.netlify.app/',
        repo: 'https://github.com/KhushiramMeena/Money-Tracker',
        img: 'https://user-images.githubusercontent.com/68834718/152794002-0e7bc583-084b-4c39-83bb-d82d5dd642b2.png',
        year: 2022,
        tags: ['React', 'Sass', 'JS'],
    },
    {
        id: getId(),
        name: 'Mini Social Media',
        url: 'https://weather-kv.netlify.app/',
        repo: 'https://github.com/KhushiramMeena/weather-app',
        img: 'https://user-images.githubusercontent.com/68834718/148419702-491fa08d-e520-4e2f-b219-374ec7118b2b.png',
        year: 2022,
        tags: ['Html', 'sass', 'JS', 'jQuery'],
    },
    {
        id: getId(),
        name: 'College Management System',
        url: 'https://blogr-kv.netlify.app/',
        repo: 'https://github.com/KhushiramMeena/blogr-landing-page',
        img: 'https://user-images.githubusercontent.com/68834718/210222542-6455303d-c93e-430b-a5c8-96a431044184.png',
        year: 2021,
        tags: ['html', 'sass', 'JS'],
    },
    // {
    //     id: getId(),
    //     name: '',
    //     url: 'https://natours-kv.netlify.app/',
    //     repo: 'https://github.com/KhushiramMeena/natours',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
    //     year: 2021,
    //     tags: ['html', 'sass', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'nexter',
    //     url: 'https://KhushiramMeena.github.io/nexter/',
    //     repo: 'https://github.com/KhushiramMeena/nexter',
    //     img: 'https://user-images.githubusercontent.com/68834718/210224671-5501c5d9-a8d2-4044-a14c-38fb7e46a113.png',
    //     year: 2021,
    //     tags: ['html', 'sass'],
    // },
    // {
    //     id: getId(),
    //     name: 'IP address tracker',
    //     url: 'https://KhushiramMeena.github.io/ip-address-tracker/',
    //     repo: 'https://github.com/KhushiramMeena/ip-address-tracker',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223386-03bcaa20-e649-4b3d-8709-59e42c6d685a.png',
    //     year: 2021,
    //     tags: ['html', 'bootstrap', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'calculator app',
    //     url: 'https://KhushiramMeena.github.io/calculator-app/',
    //     repo: 'https://github.com/KhushiramMeena/calculator-app/',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223825-3b68d696-39c6-490c-9433-f315b7efccbd.png',
    //     year: 2021,
    //     tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'pig game',
    //     url: 'https://KhushiramMeena.github.io/pig-game/',
    //     repo: 'https://github.com/KhushiramMeena/pig-game',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223527-de7fde7a-244e-4db5-8e33-d561afad6084.png',
    //     year: 2021,
    //     tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'bankist marketing',
    //     url: 'https://KhushiramMeena.github.io/bankist-marketing/',
    //     repo: 'https://github.com/KhushiramMeena/bankist-marketing',
    //     img: 'https://user-images.githubusercontent.com/68834718/210225545-989f79c3-cf05-4c53-b48e-b21f373b3734.png',
    //     year: 2021,
    //     tags: ['html', 'CSS', 'JS'],
    // },
    ],
};